from django.conf import settings

PAGINATION_SETTINGS = getattr(settings, 'PAGINATION_SETTINGS', {})

MAX_PAGES_DISPLAYED = PAGINATION_SETTINGS.get('MAX_PAGES_DISPLAYED', 10)
MARGIN_PAGES_DISPLAYED = PAGINATION_SETTINGS.get('MARGIN_PAGES_DISPLAYED', 2)
